name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t c-app .
          docker build -t m00de994/test1/c-app:$GITHUB_SHA .

    
